[package]
name = "island-ru"
version = "0.1.0"
authors = ["Cod3rkane <jcesar.developer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = "0.39.0"
gl = "0.14.0"
cgmath = "0.17.0"
